"""tables upgrade

Revision ID: 0c8067e4add4
Revises: e176f195843b
Create Date: 2024-09-25 16:38:41.006958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8067e4add4'
down_revision: Union[str, None] = 'e176f195843b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_transcript'), 'transcripts', ['transcript'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_answer'), 'questions', ['answer'], unique=False)
    op.create_index(op.f('ix_questions_question'), 'questions', ['question'], unique=False)
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_created')
    op.drop_index(op.f('ix_questions_question'), table_name='questions')
    op.drop_index(op.f('ix_questions_answer'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_transcripts_transcript'), table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
