"""tables upgrade v3

Revision ID: 75e7ac09c947
Revises: 7f10e7e85551
Create Date: 2024-09-26 16:08:37.847181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e7ac09c947'
down_revision: Union[str, None] = '7f10e7e85551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('complete', sa.Boolean(), nullable=True))
    op.drop_index('ix_questions_answer', table_name='questions')
    op.drop_index('ix_questions_question', table_name='questions')
    op.add_column('transcripts', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_transcripts_title'), 'transcripts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_title'), table_name='transcripts')
    op.drop_column('transcripts', 'title')
    op.create_index('ix_questions_question', 'questions', ['question'], unique=False)
    op.create_index('ix_questions_answer', 'questions', ['answer'], unique=False)
    op.drop_column('questions', 'complete')
    # ### end Alembic commands ###
