"""tables upgrade v2

Revision ID: 7f10e7e85551
Revises: 37ccb4aece15
Create Date: 2024-09-25 22:28:50.509327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f10e7e85551'
down_revision: Union[str, None] = '37ccb4aece15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcripts_transcript', table_name='transcripts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transcripts_transcript', 'transcripts', ['transcript'], unique=False)
    # ### end Alembic commands ###
